### ISSUE TITLE
Add demonstration with Flux

### ISSUE THREAD

**Issue by justin808** [justin808/react-webpack-rails-tutorial#13]
We could have a simple example of using flux to manage the data of the comments.

http://facebook.github.io/flux/docs/overview.html#content

This is *the way* I handle UIs. I do not use direct JSON calls from the react components.

**Comment by justin808** [comment]
This looks like a nice example and setup of using Flux: https://github.com/formidablelabs/biff and this looks like a good way to set this up: https://github.com/kenwheeler/biff-boilerplate/blob/master/package.json. Any opinions on if I should adopt these in my https://github.com/justin808/react-webpack-rails-tutorial/?

**Comment by justin808** [comment]
Another option is: https://github.com/goatslacker/alt. @bdefore recommended it.

**Comment by mbreining** [comment]
Start integrating Alt. See https://github.com/justin808/react-webpack-rails-tutorial/tree/feature/flux_integration

**Comment by justin808** [comment]
Fixed with #28
