### ISSUE TITLE
Consider Having Development Rails Load Assets from the Webpack Dev Server

### ISSUE THREAD

**Issue by justin808** [justin808/react-webpack-rails-tutorial#14]
There's some techniques in this article that are worth exploring.

http://kevinold.com/2015/02/04/configure-webpack-dev-server-and-react-hot-loader-with-ruby-on-rails.html

**Comment by DavydenkovM** [comment]
Thanks for you guide, it is very helpful!

But what about this issue? Is there any way to configure rails server to understand notifications emitted by Webpack Development server.

I don't understand how to explain rails to send requests for updated assets. Do I need to modify manifest files?

**Comment by justin808** [comment]
Incidentally, so far, we've found that it's not particularly useful to be doing hot-reload with rails. Instead, be testing in node.js mode for prototyping, and using Rails for the full stack. No half and half.
