### ISSUE TITLE
Document that non-production builds will create large bundle files

### ISSUE THREAD

**Issue by bdefore** [justin808/react-webpack-rails-tutorial#18]
Maybe because I'm just familiarizing myself with webpack, but I had to dig around for a while wondering why a very minimal project was generating a 4.5MB bundle.js and noticed that it was due to webpack.rails.config.js setting devtools to "eval-source-map" (which brought that down to 500kb).

**Comment by justin808** [comment]
@bdefore I'm pretty sure this doesn't happen on production.

**Comment by bdefore** [comment]
Yes, the flag is there to only activate when there is a build pack
configured. But I think it's easy to miss and hard to diagnose.

**Comment by justin808** [comment]
@bdefore Correct. When the build pack is configured, no map is created.
