### ISSUE TITLE
Alt Question: Code in actions

### ISSUE THREAD

**Issue by justin808** [justin808/react-webpack-rails-tutorial#36]
@mbreining Question on what code goes into the actions...

https://github.com/justin808/react-webpack-rails-tutorial/blob/master/client/assets/javascripts/actions/FormActions.js#L23

Should dispatching happen after callbacks handled?

@goatslacker, any opinion on how much code goes into actions vs. is activated by listening?

![formactions_js_-_react-rails-tutorial_-____j_react_react-webpack-rails-tutorial_](https://cloud.githubusercontent.com/assets/1118459/7753590/1c5a964e-ff82-11e4-85bc-29ac7b37f815.jpg)

**Comment by mbreining** [comment]
@justin808 I think this is the right sequence. We want to dispatch first so that we can display a spinner image while the comment gets submitted - for example.

**Comment by goatslacker** [comment]
This looks correct you want to dispatch to signify "loading" and then other actions would kick off for success/fail

**Comment by justin808** [comment]
Sweet! Thanks @mbreining and @goatslacker
