### ISSUE TITLE
Try out with Zurb Foundtion

### ISSUE THREAD

**Issue by justin808** [justin808/react-webpack-rails-tutorial#39]
Seems that Twitter Bootstrap is going to be a while before it supports flexbox.

So let's try out Zurb! I'm thinking a fork of this project, but it may not get merged into master. Instead, we can have a branch master-zurb for the zurb version. 

* http://foundation.zurb.com/
* http://webrafter.com/opensource/react-foundation-apps
* http://react.rocks/example/react-foundation-apps

**Comment by joseluistorres** [comment]
@justin808 I can help with that

**Comment by justin808** [comment]
@joseluistorres Awesome! I'll help as well!

**Comment by joseluistorres** [comment]
@justin808 ok I forked the repo and have it running locally with everything, hot module it's amazing, should I start with a branch using only the foundation stuff? or moving straight to use react-foundation-apps ?

**Comment by justin808** [comment]
Yes on branch using foundation. Sure, try out react foundation apps. I'm not sure if that is the way to go. Looking for advice.

**Comment by joseluistorres** [comment]
ok copy that!

**Comment by joseluistorres** [comment]
I found a way testing this:
http://foundation.webrafter.com/blog/2015/1/5/getting-started-with-react-foundation-apps
https://github.com/akiran/generator-react-foundation-apps
I'm going to check to can integrate it to the existing stuff.

**Comment by justin808** [comment]
@joseluistorres, @dpindrys (David) would like to collaborate with you on figuring out how to make this work with react, webpack, and Rails.

**Comment by justin808** [comment]
@joseluistorres, is this helpful? http://www.angularonrails.com/ruby-on-rails-angularjs-single-page-application/

Yes, it's angular, but maybe some of the techniques? But maybe not since we're using React with Webpack. A tutorial in this area is definitely needed!

**Comment by joseluistorres** [comment]
hi @dpindrys let's do this! , I'll take a look at that too @justin808 thanks!

**Comment by justin808** [comment]
@joseluistorres @dpindrys @ben-ward  I'm feeling that we close this for now unless there's any good reason to investigate this further now.

**Comment by joseluistorres** [comment]
I believe so, imho it seems that this would need to be two separate apps, front-end and backend, perhaps will be out of the scope of the existing example with react-rails-webpack :flushed:

**Comment by justin808** [comment]
My original main goal was figuring out the strategy in terms of flex-box, since zurb seemed to support that. So closing for now. If anybody wants to re-open, let me know.
