### ISSUE TITLE
Add Codeship CI integration

### ISSUE THREAD

**Issue by justin808** [justin808/react-webpack-rails-tutorial#42]
https://travis-ci.org/

Setting this up!

**Comment by justin808** [comment]
Anybody knowledgeable about setting up multi-language Travis? @mbreining?

**Comment by justin808** [comment]
Seems to be a couple ways to do this with 2 languages.

1. this is how to install a gem in `before_install` -- maybe we could do this for npm files? http://stackoverflow.com/a/21761205/1009332
2. Have the rake task for running the tests build the webpack `../app/assets/javascripts/generated/client-bundle.js'`

**Comment by justin808** [comment]
@mbreining @dylangrafmyre We'll probably use Codeship, as that's what we're using on a similar project so we know how to set it up.

**Comment by geminiyellow** [comment]
+1 i need this help.

**Comment by justin808** [comment]
@dylangrafmyre Just set us up with codeship...

Dylan, we should write a quick article on how to do this!
