### ISSUE TITLE
Small UI enhancements

### ISSUE THREAD

**Issue by justin808** [justin808/react-webpack-rails-tutorial#49]
Live deployment is at http://www.reactrails.com/

1. Rake task to delete all comments older than one day (couple different options, such as scheduled running of rake task). Provide instructions on how to setup in Heroku Scheduler.
3. Note that comments older than 24 hours deleted.

@johnnycus will work on this.

**Comment by Johnnycus** [comment]
@justin808 👍

**Comment by justin808** [comment]
Fixed by #62
